apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: ciml-run-training
spec:
  inputs:
    params:
    - name: dataset
      description: Name of the dataset
    - name: experiment
      description: Name of the experiment
    resources:
    - name: ciml
      type: git
    - name: dataset
      type: storage
      targetPath: data/dataset
    - name: experiments
      type: storage
      targetPath: data/_experiments
  outputs:
    resources:
    - name: cimloutput
      type: storage
  steps:

  - name: run-ciml
    image: us.icr.io/ciml/ciml-base:manual2
    workingDir: $(inputs.resources.ciml.path)
    env:
    - name: PYTHONPATH
      value: $(inputs.resources.ciml.path)
    - name: LC_ALL
      value: C.UTF-8
    - name: LANG
      value: C.UTF-8
    command:
    - /bin/bash
    args:
    - -ce
    - |
      DATA_DIR=$(dirname $(inputs.resources.dataset.path))
      ln -s $(inputs.resources.dataset.path) $DATA_DIR/$(inputs.params.dataset)

      python ciml/trainer.py local_trainer \
        --dataset "$(inputs.params.dataset)" \
        --experiment "$(inputs.params.experiment)" \
        --data-path $DATA_DIR

      mv $(inputs.resources.ciml.path)/data $(outputs.resources.cimloutput.path)/
